swagger.controller.base.package.name=com.neo.v1.controller
springfox.documentation.swagger.v2.path=/product-catalogue/api-docs
swagger.api.host=bankabc-test.apigee.net
swagger.api.info.title=Product Catalogue service
swagger.api.info.description=.
swagger.api.info.version=1.0